### PR TITLE
feature/integrate Dockerfile for building a docker image

### PR DESCRIPTION
**Pull request by maxkratz**
Hey @jstayton,

I've created a `Dockerfile` to build a docker image for suri. There are also some new commands in the readme file. Please let me know if you require some changes.

Max

### CODE REVIEW

**Comment by jstayton** [comment]
Hey Max,

Thanks for this!

I'm not super up-to-speed with the latest in the world of Docker – other than using Compose to run dependencies like databases and such – so let me digest this for a bit.

One initial question: Is this meant for easier development, or deploys to production, or both?

Thanks again!

**Comment by maxkratz** [comment]
You're welcome!

To answer your question: The reason to build this image (at least for me) was deployment to production. By using this image, I do not have to install nodejs on my server. Furthermore, it is easier to build the static site with CI, because the CI does not have to install all dependencies of your project for each commit in pipeline.

**Comment by maxkratz** [comment]
Some changes to this PR:
- Updated the Docker base image from Ubuntu 20.04 to Ubuntu 22.04
- Updated the used Node version to 14 (because suri only works for >=14)

Any news on merging this?

**Comment by jstayton** [comment]
Hey Max,

Sorry for never getting around to this. Docker was never a deployment method that I needed, so it wasn't a priority for me.

That said, I recently came back to this project and re-built it from scratch for an official v1. There's now [a template repository for deploying with Docker](https://github.com/surishortlink/suri-deploy-docker) (among other methods).

Give that a look and see if it's something you can use. Or just stick with what you've got since it works!

**Pull request closed without merging**
